/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 floor.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useBox } from '@react-three/cannon'

export function Floor(props) {
  const { nodes, materials } = useGLTF('/floor.gltf')
  const [ref] = useBox(() => ({
    type: "Static",
    args: [40, 0.4, 40],
  }));

  return (
    <group {...props} dispose={null} ref={ref}>
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.005']} scale={[20, 0.2, 20]}/>
    </group>
  )
}

useGLTF.preload('/floor.gltf')
