/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 wall.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/wall.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.006']} position={[19.8, 2, 13]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[7, 0.2, 2.2]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.006']} position={[0, 2, -19.8]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[20, 0.2, 2.2]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.006']} position={[0, 2, 19.8]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[20, 0.2, 2.2]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.006']} position={[-20.2, 2, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[20, 0.2, 2.2]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials['Material.006']} position={[19.8, 2, -13]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[7, 0.2, 2.2]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials['Material.006']} position={[9, 2, -13]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[7, 0.1, 2.2]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials['Material.006']} position={[9, 2, 13]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[7, 0.1, 2.2]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials['Material.006']} position={[-1.8, 2, 13]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[7, 0.1, 2.2]} />
      <mesh geometry={nodes.Cube011.geometry} material={materials['Material.006']} position={[-1.8, 2, -13]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[7, 0.1, 2.2]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials['Material.006']} position={[19, 1.12, 12.815]} scale={[0.7, 0.1, 6.81]} />
      <mesh geometry={nodes.Cube013.geometry} material={materials['Material.006']} position={[9.755, 1.12, 12.815]} scale={[0.7, 0.1, 6.81]} />
      <mesh geometry={nodes.Cube014.geometry} material={materials['Material.006']} position={[-1.028, 1.12, 12.815]} scale={[0.7, 0.1, 6.81]} />
      <mesh geometry={nodes.Cube015.geometry} material={materials['Material.006']} position={[8.217, 1.12, 12.815]} scale={[0.7, 0.1, 6.81]} />
      <mesh geometry={nodes.Cube016.geometry} material={materials['Material.006']} position={[8.217, 1.12, -12.811]} scale={[0.7, 0.1, 6.81]} />
      <mesh geometry={nodes.Cube017.geometry} material={materials['Material.006']} position={[-1.028, 1.12, -12.811]} scale={[0.7, 0.1, 6.81]} />
      <mesh geometry={nodes.Cube018.geometry} material={materials['Material.006']} position={[9.755, 1.12, -12.811]} scale={[0.7, 0.1, 6.81]} />
      <mesh geometry={nodes.Cube019.geometry} material={materials['Material.006']} position={[19, 1.12, -12.811]} scale={[0.7, 0.1, 6.81]} />
    </group>
  )
}

useGLTF.preload('/wall.gltf')
